# mysql 配置

version: '2'
services:
  mysql:
    image: mysql:5.7
    command: [
              '--character-set-server=utf8',
              '--collation-server=utf8_general_ci',
              '--default-time-zone=+8:00' # 这句不是重点
            ]
    container_name: local_mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./root:/root
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: root
#      MYSQL_USER: vic
#      MYSQL_PASSWORD: android
  adminer:
      image: adminer
      restart: always
      ports:
        - 8079:8080
