# mysql 配置

version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: local_mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./root:/root
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: root
#      MYSQL_USER: vic
#      MYSQL_PASSWORD: android
  adminer:
      image: adminer
      restart: always
      ports:
        - 8079:8080
